services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true


##### Twig Extension detected
  Austral\ToolsBundle\TwigExtension\ToolsTwig:  "@twig.extension.tools"
  twig.extension.tools:
    class:        Austral\ToolsBundle\TwigExtension\ToolsTwig
    arguments:    ['%kernel.project_dir%']
    tags:
      - { name: twig.extension }

##### Debug
  Austral\ToolsBundle\Services\Debug: "@austral.tools.debug"
  austral.tools.debug:
    class:        Austral\ToolsBundle\Services\Debug
    calls:
      - [ setDebugStopWatch, ['@?debug.stopwatch'] ]

##### Services
  Austral\ToolsBundle\Services\ServicesStatusChecker: "@austral.tools.services.status-checker"
  austral.tools.services.status-checker:
    class:        Austral\ToolsBundle\Services\ServicesStatusChecker
    arguments:    ['@service_container']


####### gedmo.listener default configuration
  gedmo.listener.tree:
    class: Gedmo\Tree\TreeListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]

  gedmo.listener.translatable:
    class: Gedmo\Translatable\TranslatableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]
      - [ setDefaultLocale, [ "%kernel.default_locale%" ] ]
      - [ setTranslationFallback, [ false ] ]

  gedmo.listener.timestampable:
    class: Gedmo\Timestampable\TimestampableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]

  gedmo.listener.sluggable:
    class: Gedmo\Sluggable\SluggableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]

  gedmo.listener.sortable:
    class: Gedmo\Sortable\SortableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]

  gedmo.listener.loggable:
    class: Gedmo\Loggable\LoggableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]